SKILLS = [
    "python",
    "java",
    "c",
    "c++",
    "sql",
    "html",
    "css",
    "javascript",
    "react",
    "nodejs",
    "node.js",
    "express",
    "mongodb",
    "mysql",
    "git",
    "github",
    "docker",
    "aws",
    "azure",
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "tensorflow",
    "keras",
    "machine learning",
    "deep learning",
    "data analysis",
    "streamlit",
    "flask",
    "django"
]